def configure(conf):
	pass


def build(bld):
	source = ['gstimxdmabufferallocator.c', 'gstimxdefaultallocator.c']
	install_files = ['gstimxdmabufferallocator.h', 'gstimxdefaultallocator.h']
	if bld.env['ENABLE_GST_ION_ALLOCATOR']:
		source += ['gstimxionallocator.c']
		install_files += ['gstimxionallocator.h']
	bld(
		features = ['c', 'cshlib'],
		includes = ['.', '../../..'],
		uselib = bld.env['COMMON_USELIB'] + ['IMXDMABUFFER'],
		source = source,
		name = 'gstimxcommon',
		target = 'gstimxcommon',
		install_path="${LIBDIR}",
		vnum = bld.env['GSTREAMER_IMX_VERSION']
	)

	bld(
		source = 'gstimxcommon.pc.in',
		target = 'gstimxcommon.pc',
		VERSION = bld.env['GSTREAMER_IMX_VERSION'],
        LIBS = '-lgstimxcommon',
		install_path="${LIBDIR}/pkgconfig"
	)

	bld.install_files('${PREFIX}/include/gstreamer-1.0/gst/imx', install_files)
