#!/usr/bin/env python


def configure(conf):
	pass


def build(bld):
	bld(
		features = ['c', 'cshlib'],
		includes = ['.', '../..'],
		uselib = bld.env['COMMON_USELIB'] + ['FSLVPUWRAPPER'],
		use = 'gstfslcommon',
		target = 'gstfslvpu',
		source = bld.path.ant_glob('*.c') + bld.path.ant_glob('decoder/*.c'),
		install_path = bld.env['PLUGIN_INSTALL_PATH']
	)

