#!/usr/bin/env python


def configure(conf):
	conf.check_cfg(package = 'libfslvpuwrap >= 1.0.45', uselib_store = 'FSLVPUWRAPPER', args = '--cflags --libs', mandatory = 1)


def build(bld):
	bld(
		features = ['c', 'cshlib'],
		includes = ['.', '../..'],
		uselib = bld.env['COMMON_USELIB'] + ['FSLVPUWRAPPER'],
		use = 'gstimxcommon',
		target = 'gstimxvpu',
		source = bld.path.ant_glob('*.c') + bld.path.ant_glob('decoder/*.c') + bld.path.ant_glob('encoder/*.c'),
		install_path = bld.env['PLUGIN_INSTALL_PATH']
	)

