#!/usr/bin/env python


def configure(conf):
	from waflib.Build import Logs
	if conf.check_cc(fragment = '''
		#include <sys/types.h>
		#include <linux/fb.h>
		#include <linux/ipu.h>

		int main() { return 0; }
		''',
		uselib_store = 'IMXIPU',
		uselib = 'KERNEL_HEADERS',
		mandatory = False,
		execute = False,
		msg = 'checking for linux/fb.h and the IPU header linux/ipu.h'
	):
		Logs.pprint('GREEN', 'IPU sink will be built')
		conf.env['IPUSINK_ENABLED'] = 1
	else:
		Logs.pprint('RED', 'IPU sink will not be built - headers not found')


def build(bld):
	if bld.env['IPUSINK_ENABLED']:
		bld(
			features = ['c', 'cshlib'],
			includes = ['.', '../..'],
			uselib = bld.env['COMMON_USELIB'] + ['IMXIPU', 'KERNEL_HEADERS'],
			use = 'gstimxcommon',
			target = 'gstimxipu',
			source = bld.path.ant_glob('*.c') + bld.path.ant_glob('videotransform/*.c') + bld.path.ant_glob('sink/*.c'),
			install_path = bld.env['PLUGIN_INSTALL_PATH']
		)

