#!/usr/bin/env python


def options(opt):
	opt.add_option('--kernel-headers', action = 'store', default = None, help = 'specify path to the kernel headers')


def configure(conf):
	import os
	from waflib.Build import Logs
	incpaths = []
	notfound = None
	if conf.options.kernel_headers:
		incpaths += [os.path.abspath(os.path.expanduser(conf.options.kernel_headers))]
	if conf.check_cc(fragment = '''
		#include <sys/types.h>
		#include <linux/mxcfb.h>
		#include <linux/ipu.h>

		int main() { return 0; }
		''',
		uselib_store = 'FSLIPU',
		includes = incpaths,
		mandatory = False,
		execute = False,
		msg = 'checking for IPU headers linux/mcxfb.h and linux/ipu.h'
	):
		Logs.pprint('GREEN', 'IPU sink will be built')
		conf.env['IPUSINK_ENABLED'] = 1
	else:
		Logs.pprint('RED', 'IPU sink will not be built - headers not found')


def build(bld):
	if bld.env['IPUSINK_ENABLED']:
		bld(
			features = ['c', 'cshlib'],
			includes = ['.', '../..'],
			uselib = bld.env['COMMON_USELIB'] + ['FSLIPU'],
			use = 'gstfslcommon',
			target = 'gstfslipu',
			source = bld.path.ant_glob('*.c') + bld.path.ant_glob('videotransform/*.c') + bld.path.ant_glob('sink/*.c'),
			install_path = bld.env['PLUGIN_INSTALL_PATH']
		)

