#!/usr/bin/env python


def configure(conf):
	pass


def build(bld):
	bld(
		features = ['c', bld.env['CLIBTYPE']],
		includes = ['.', '../..'],
		uselib = bld.env['COMMON_USELIB'],
		use = 'gstimxcommon',
		target = 'gstimxv4l2videosrc',
		source = bld.path.ant_glob('*.c'),
		install_path = bld.env['PLUGIN_INSTALL_PATH']
	)

