#!/usr/bin/env python


def configure(conf):
	pass


def build(bld):
	bld(
		features = ['c', 'cshlib'],
		includes = ['.', '../..'],
		uselib = bld.env['COMMON_USELIB'],
		use = 'gstfslcommon',
		target = 'gstfsldecoder',
		source = bld.path.ant_glob('*.c'),
		install_path = bld.env['PLUGIN_INSTALL_PATH']
	)

