#!/usr/bin/env python


def configure(conf):
	pass


def build(bld):
	import os
	bld(
		features = ['c', bld.env['CLIBTYPE']],
		includes = ['.', '../..'],
		uselib = bld.env['COMMON_USELIB'],
		target = 'gstimxcommon',
		vnum = '0.9.9',
		source = bld.path.ant_glob('*.c'),
		install_path = os.path.join(bld.env['PREFIX'], 'lib')
	)

